### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by danielgreyio** [deepworks-net/docker-webdna-demo#3]
# WebDNA Docker Container Roadmap
- [ ] #50
    - [ ] #48
    - [ ] #49
- [ ] Add Containers for AlmaLinux 8.5
    - [X] #5
    - [X] #6
    - [X] #7
    - [X] #8
    - [ ] Add Container for AlmaLinux 8.5 Server 8.6.5
    - [ ] Add Container for AlmaLinux 8.5 Server 8.6.4
    - [ ] Add Container for AlmaLinux 8.5 Server 8.6.3
    - [ ] Add Container for AlmaLinux 8.5 Server 8.6.1
- [ ] Add Containers for Alpine 3.12
    - [X] #9
    - [ ] Add Container for Alpine 3.12 Server 8.6.5
- [ ] Add Containers for Alpine 3.21
    - [ ] #4
- [ ] Add Containers for CentOS 7
    - [X] #10
    - [X] #11
    - [X] #12
    - [X] #13
    - [ ] Add Container for CentOS 7 Server 8.6.5
    - [ ] Add Container for CentOS 7 Server 8.6.4
    - [ ] Add Container for CentOS 7 Server 8.6.3
    - [ ] Add Container for CentOS 7 Server 8.6.1
- [ ] Add Containers for CentOS 8 (Vault)
    - [X] #14
    - [X] #15
    - [X] #16
    - [X] #17
    - [ ] Add Container for CentOS 8 Server 8.6.5
    - [ ] Add Container for CentOS 8 Server 8.6.4
    - [ ] Add Container for CentOS 8 Server 8.6.3
    - [ ] Add Container for CentOS 8 Server 8.6.1
- [ ] Add Containers for CentOS (8) Stream
    - [ ] Add Container for CentOS (8) Stream FCGI 8.6.5
    - [ ] Add Container for CentOS (8) Stream FCGI 8.6.4
    - [ ] Add Container for CentOS (8) Stream FCGI 8.6.3
    - [ ] Add Container for CentOS (8) Stream FCGI 8.6.1
    - [ ] Add Container for CentOS (8) Stream Server 8.6.5
    - [ ] Add Container for CentOS (8) Stream Server 8.6.4
    - [ ] Add Container for CentOS (8) Stream Server 8.6.3
    - [ ] Add Container for CentOS (8) Stream Server 8.6.1
- [ ] Add Containers for RockyLinux 8.5
    - [X] #18
    - [X] #19
    - [X] #20
    - [X] #21
    - [ ] Add Container for RockyLinux 8.5 Server 8.6.5
    - [ ] Add Container for RockyLinux 8.5 Server 8.6.4
    - [ ] Add Container for RockyLinux 8.5 Server 8.6.3
    - [ ] Add Container for RockyLinux 8.5 Server 8.6.1
- [ ] Add Containers for Ubuntu 16.04
    - [X] #22
    - [X] #23
    - [X] #24
    - [X] #25
    - [ ] Add Container for Ubuntu 16.04 Server 8.6.5
    - [ ] Add Container for Ubuntu 16.04 Server 8.6.4
    - [ ] Add Container for Ubuntu 16.04 Server 8.6.3
    - [ ] Add Container for Ubuntu 16.04 Server 8.6.1
- [ ] Add Containers for Ubuntu 18.04
    - [X] #26
    - [X] #27
    - [X] #28
    - [X] #29
    - [ ] Add Container for Ubuntu 18.04 Server 8.6.5
    - [ ] Add Container for Ubuntu 18.04 Server 8.6.4
    - [ ] Add Container for Ubuntu 18.04 Server 8.6.3
    - [ ] Add Container for Ubuntu 18.04 Server 8.6.1
- [ ] Add Containers for Ubuntu 20.04
    - [X] #30
    - [X] #31
    - [X] #32
    - [X] #33
    - [ ] Add Container for Ubuntu 20.04 Server 8.6.5
    - [ ] Add Container for Ubuntu 20.04 Server 8.6.4
    - [ ] Add Container for Ubuntu 20.04 Server 8.6.3
    - [ ] Add Container for Ubuntu 20.04 Server 8.6.1
- [ ] Add Containers for Ubuntu 21.10
    - [X] #34
    - [X] #36
    - [X] #37
    - [X] #38
    - [ ] Add Container for Ubuntu 21.10 Server 8.6.5
    - [ ] Add Container for Ubuntu 21.10 Server 8.6.4
    - [ ] Add Container for Ubuntu 21.10 Server 8.6.3
    - [ ] Add Container for Ubuntu 21.10 Server 8.6.1
- [ ] Add Containers for Ubuntu 22.04
    - [X] #35
    - [X] #39
    - [X] #40
    - [X] #41
    - [ ] Add Container for Ubuntu 22.04 Server 8.6.5
    - [ ] Add Container for Ubuntu 22.04 Server 8.6.4
    - [ ] Add Container for Ubuntu 22.04 Server 8.6.3
    - [ ] Add Container for Ubuntu 22.04 Server 8.6.1
- [ ] Add Containers for Oracle Linux 7.9
    - [ ] Add Container for Oracle Linux 7.9 FCGI 8.6.5
    - [ ] Add Container for Oracle Linux 7.9 FCGI 8.6.4
    - [ ] Add Container for Oracle Linux 7.9 FCGI 8.6.3
    - [ ] Add Container for Oracle Linux 7.9 FCGI 8.6.1
    - [ ] Add Container for Oracle Linux 7.9 Server 8.6.5
    - [ ] Add Container for Oracle Linux 7.9 Server 8.6.4
    - [ ] Add Container for Oracle Linux 7.9 Server 8.6.3
    - [ ] Add Container for Oracle Linux 7.9 Server 8.6.1
- [ ] Add Containers for Oracle Linux 8.5
    - [ ] Add Container for Oracle Linux 8.5 FCGI 8.6.5
    - [ ] Add Container for Oracle Linux 8.5 FCGI 8.6.4
    - [ ] Add Container for Oracle Linux 8.5 FCGI 8.6.3
    - [ ] Add Container for Oracle Linux 8.5 FCGI 8.6.1
    - [ ] Add Container for Oracle Linux 8.5 Server 8.6.5
    - [ ] Add Container for Oracle Linux 8.5 Server 8.6.4
    - [ ] Add Container for Oracle Linux 8.5 Server 8.6.3
    - [ ] Add Container for Oracle Linux 8.5 Server 8.6.1
- [ ] Add Containers for Fedora
    - [ ] Add Container for Fedora FCGI 8.6.5
    - [ ] Add Container for Fedora FCGI 8.6.4
    - [ ] Add Container for Fedora FCGI 8.6.3
    - [ ] Add Container for Fedora FCGI 8.6.1
    - [ ] Add Container for Fedora Server 8.6.5
    - [ ] Add Container for Fedora Server 8.6.4
    - [ ] Add Container for Fedora Server 8.6.3
    - [ ] Add Container for Fedora Server 8.6.1
- [ ] Add Containers for Debian
    - [ ] Add Container for Debian FCGI 8.6.5
    - [ ] Add Container for Debian FCGI 8.6.4
    - [ ] Add Container for Debian FCGI 8.6.3
    - [ ] Add Container for Debian FCGI 8.6.1
    - [ ] Add Container for Debian Server 8.6.5
    - [ ] Add Container for Debian Server 8.6.4
    - [ ] Add Container for Debian Server 8.6.3
    - [ ] Add Container for Debian Server 8.6.1
- [ ] Add Containers for Httpd Container Image
    - [ ] Add Container for Httpd FCGI 8.6.5
    - [ ] Add Container for Httpd FCGI 8.6.4
    - [ ] Add Container for Httpd FCGI 8.6.3
    - [ ] Add Container for Httpd FCGI 8.6.1
    - [ ] Add Container for Httpd Server 8.6.5
    - [ ] Add Container for Httpd Server 8.6.4
    - [ ] Add Container for Httpd Server 8.6.3
    - [ ] Add Container for Httpd Server 8.6.1
